
const actionTypes = {
    'SET_CURRENT_USER': 'SET_CURRENT_USER',

    'TOGGLE_CART_DROPDOWN': 'TOGGLE_CART_DROPDOWN',
    'ADD_CART_ITEM': 'ADD_CART_ITEM',
    'REMOVE_ITEM_FROM_CART': 'REMOVE_ITEM_FROM_CART',
    'DECREASE_ITEM_FROM_CART': 'DECREASE_ITEM_FROM_CART'
}

export default actionTypes;